### ISSUE TITLE
Can this tool be used for face registration?

### ISSUE THREAD

**Issue by kuangcy1998** [Juyong/Fast_RNRR#1]
Hi, thanks for your outstanding work. I have a series of 3D face scans and I want to do face registration by fitting a mesh template(like BFM model) on the scans. Can this tool  be used for this process? Thanks.

**Comment by Juyong** [comment]
Hi, thanks for your interests to our work. Yes, you can apply our code to your problem, and I guess some sparse landmarks could help the fitting results.
