### ISSUE TITLE
The runtime of the function Prune::Initialize()

### ISSUE THREAD

**Issue by sun6s** [Juyong/Fast_RNRR#14]
when I try to use the old version with the SHOT feature and diffusion pruning, the function Prune::Initialize(hgeodesic* geo, VPairs& corres, double c_0) takes about 30s to Initialize. Is this normal?

**Comment by yaoyx689** [comment]
The time is related to the size of your input source and target models. 

These two operations involve calculating the SHOT feature on the two meshes respectively,  and some global geodesic distances. If there are many vertices of the input two meshes, it will take a long time and it is normal.
