### ISSUE TITLE
Unexpected end of file while reading.

### ISSUE THREAD

**Issue by Curveaddicted** [Juyong/Fast_RNRR#17]
hello，thank you for your work!
I made a model myself for testing, but it seems a little problem. I use your **test** data and runs a perfect result. But use my own design model it suggests:
 `Custom face Properties defined, before 'vertex_indices' property was defined. They will be skipped.`
`Custom face Properties defined, before 'vertex_indices' property was defined. They will be skipped.`
`Unexpected end of file while reading.`
Can you tell me how to solve it? Thank you!

**Comment by yaoyx689** [comment]
This may be a problem with the format of the input model. You can test whether your model can be read normally by `openmesh`.

**Comment by Curveaddicted** [comment]
> This may be a problem with the format of the input model. You can test whether your model can be read normally by `openmesh`.

yes,I change the format from `.PLY` to `.obj` , and it worked and showed me the outputres. THANK YOU!
