### ISSUE TITLE
About test model

### ISSUE THREAD

**Issue by Curveaddicted** [Juyong/Fast_RNRR#18]
hello!it's me again. I checked the **test data** and noticed that the source and target mesh has the same vertex\face\edge\half edge. so my question is did you guys use some methods to initialize the model? if so ,which method did you use or how you accomplish it?

Because for my **design model** which has   
_Vertex:8 face:12 edge: 18 half_edge: 36_
and I change it a little bit, the **changed model** has
_Vertex:3645 face:7286 edge: 10929 half_edge: 21858_

It dosen't working for my designed model.

**Comment by yaoyx689** [comment]
The datasets we tested have the same vertex\edge\face, we didn't do additional processing. But in the test data there are whole-to-partial examples with different vertex number, this is constructed by removing some points from the original model.
