### ISSUE TITLE
face registration result is very bad

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [Juyong/Fast_RNRR#3]
the result in face registration is very bad, like follow, 134 landmarks is used:
source:
![image](https://user-images.githubusercontent.com/30692249/84242544-8e75fb80-ab33-11ea-8daf-78381fe3c10e.png)
target:
![image](https://user-images.githubusercontent.com/30692249/84242879-03493580-ab34-11ea-922f-71de11f5552f.png)
nricp result:
![image](https://user-images.githubusercontent.com/30692249/84242778-e3197680-ab33-11ea-8330-715bfdb6d12c.png)
fast rnrr result:
![image](https://user-images.githubusercontent.com/30692249/84242761-dbf26880-ab33-11ea-9de0-ac83e7deaacd.png)

**Comment by ZHANG-SHI-CHANG** [comment]
> Hi, how do you construct the correspondence between source and target models? If I understand correct, they have the same topologies. Besides, how do you set the weights?

yes, they have the same topologies, but i just use 134 landmarks, because i want to use it between different topologies. And i didn't modify the code about weights

**Comment by Juyong** [comment]
Can you send the test models and the labeled landmarks to us via juyong@ustc.edu.cn?

**Comment by ZHANG-SHI-CHANG** [comment]
> Can you send the test models and the labeled landmarks to us via [juyong@ustc.edu.cn](mailto:juyong@ustc.edu.cn)?

👌，thx~

**Comment by yaoyx689** [comment]
Hi, firstly, our method depends on geodesic calculation when sampling nodes, the geodesic code we used currently only supports closed mesh calculations, so maybe you need to fill holes first and then run it or change to a more suitable geodesic calculation method(in nodeSampler.cpp and geodesic.cpp). Secondly, the weights of regularization term and rotation term will greatly affect the results, you can adjust(decrease) them (paras.alpha and paras.beta in main.cpp) to make it more suitable for your models.

**Comment by ZHANG-SHI-CHANG** [comment]
> Hi, firstly, our method depends on geodesic calculation when sampling nodes, the geodesic code we used currently only supports closed mesh calculations, so maybe you need to fill holes first and then run it or change to a more suitable geodesic calculation method(in nodeSampler.cpp and geodesic.cpp). Secondly, the weights of regularization term and rotation term will greatly affect the results, you can adjust(decrease) them (paras.alpha and paras.beta in main.cpp) to make it more suitable for your models.

ok, i get it

**Comment by X-niper** [comment]
> > Hi, firstly, our method depends on geodesic calculation when sampling nodes, the geodesic code we used currently only supports closed mesh calculations, so maybe you need to fill holes first and then run it or change to a more suitable geodesic calculation method(in nodeSampler.cpp and geodesic.cpp). Secondly, the weights of regularization term and rotation term will greatly affect the results, you can adjust(decrease) them (paras.alpha and paras.beta in main.cpp) to make it more suitable for your models.
> 
> ok, i get it

Hi， Mr Zhang， 

Have you finally gotten good results on face registration?
