### ISSUE TITLE
After adjusting the parameters, why the running time of the algorithm is still so long？

### ISSUE THREAD

**Issue by Sunzhiliang** [Juyong/Fast_RNRR#8]
Hi, @Juyong, thanks for kindly sharing the source code.  However, when I run the new version of Fast_RNRR, the running time of the algorithm is still  long after I adjust the parameters. I don't know what caused it.
![image](https://user-images.githubusercontent.com/34574779/114494016-2e1d8200-9c4e-11eb-8dcc-451597e7f51e.png)
![image](https://user-images.githubusercontent.com/34574779/114494152-6f159680-9c4e-11eb-80c3-6a81230d84b9.png)

**Comment by yaoyx689** [comment]
Are you running in ‘’Release” mode？

**Comment by sun6s** [comment]
> Are you running in ‘’Release” mode？

Thanks ,I run in the "debug‘’ mode all the time in VS.  I have changed to the ’Release” mode. It is fast as the author said.
