### ISSUE TITLE
关于更新代码的deformation graph node生成相关的问题

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [Juyong/Fast_RNRR#9]
hi，大佬，新的代码非常给力，学习到了很多东西，这里关于node生成我有一些问题请教

1. 更新的测地线计算方法对于非闭合mesh生成的node，形变时仍有非常差的结果，尤其是对于人脸数据
2. 如果我使用别的方法生成node会对算法最终结果造成多大影响？比如使用fast_marching

**Comment by ZHANG-SHI-CHANG** [comment]
> hi，大佬，新的代码非常给力，学习到了很多东西，这里关于node生成我有一些问题请教
> 
> 1. 更新的测地线计算方法对于非闭合mesh生成的node，形变时仍有非常差的结果，尤其是对于人脸数据
> 2. 如果我使用别的方法生成node会对算法最终结果造成多大影响？比如使用fast_marching

赞！！通过修改参数达到了不错的效果，前面的问题提的草率了，大佬牛皮

**Comment by xiecookie** [comment]
想请问一下，您现在还是用的非闭合mesh吗，只用改参数不闭合mesh就能达到不错的效果吗

**Comment by ymclsh** [comment]
> > hi，大佬，新的代码非常给力，学习到了很多东西，这里关于node生成我有一些问题请教
> > 
> > 1. 更新的测地线计算方法对于非闭合mesh生成的node，形变时仍有非常差的结果，尤其是对于人脸数据
> > 2. 如果我使用别的方法生成node会对算法最终结果造成多大影响？比如使用fast_marching
> 
> 赞！！通过修改参数达到了不错的效果，前面的问题提的草率了，大佬牛皮

@ZHANG-SHI-CHANG Hi,  I tested upon scanned face objs, the result is not satisfying. Would you please share what kind of parameters adjustment you've done? Thanks
